fixed region for retrieving frontend env secret
DSGT-DLP/dlp-cli pull request #14
Opened 2024-01-07 20:06 UTC by sliu526

Fixed region for retrieving frontend env secret (from us-west-2 to us-east-1).

GitHub issue described [here](https://github.com/DSGT-DLP/dlp-cli/issues/13).

**Process**

1. Changed region in frontend.go file in dlp-cli --> cmd --> frontend from us-west-2 to us-east-1
2. Tested that the build_frontend_env command in dlp-cli works by running `go run main.go frontend build-frontend-env-file --secret "frontend_env"`
3. Encountered error messages detailed and solved in [this link](https://www.notion.so/9b6766cea0b24060bb10d806d58ee0c1?v=1c2cddea700a478a86e95a5e86c09cf8&p=66c7901f9780469ebde4d0cd669dfc87&pm=s).
4. Added fix in build-frontend-env-file to parse through key:value secret values and updated .env file
5. Tested with go script from step 2

2024-01-07 20:07 UTC, farisdurrani approved these changes, later dismissed

2024-01-07 20:22 UTC, codingwithsurya submitted a review, later dismissed
LGTM!

2024-01-07 20:25 UTC, karkir0003 requested changes
minor changes

2024-01-07 20:25 UTC, karkir0003 commented on cmd/frontend/build_frontend_env/build-frontend-env-file.go
> +    "encoding/json" // to unmarshal json
i dont think you need the // to unmarshall json comment. its a bit redundant bc your implementation explains this

2024-01-07 20:25 UTC, karkir0003 commented on cmd/frontend/build_frontend_env/build-frontend-env-file.go
> +        var secretsMap map[string]string // declares a variable of type Map with key:value as string:string
this comment is unnecessary bc this line of code is self explanatory

2024-01-07 20:25 UTC, karkir0003 commented on cmd/frontend/build_frontend_env/build-frontend-env-file.go
> +        if err := json.Unmarshal([]byte(*secretValue.SecretString), &secretsMap); err != nil { // stores unmarshalled json into secretsMap
you can remove the // stores unmarshalled json into secretsMap comment

2024-01-09 00:45 UTC, karkir0003 approved these changes
LGTM @sliu526

2024-01-09 01:00 UTC, merged